# Generated by Django 2.2.12 on 2020-05-12 13:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=20)),
                ('fotoUser', models.ImageField(default='user.png', upload_to='', verbose_name='Foto de perfil')),
                ('telUser', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreHabil', models.CharField(max_length=100)),
                ('descripcionHabil', ckeditor.fields.RichTextField(verbose_name='Descripcion habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocentajeHabil', models.DecimalField(decimal_places=1, max_digits=2)),
                ('updateHabil', models.DateTimeField(auto_now=True)),
                ('idHabili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Habilidades')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DataUser')),
            ],
        ),
        migrations.CreateModel(
            name='DetaRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addUser', models.DateTimeField(auto_now_add=True)),
                ('updateUser', models.DateTimeField(auto_now=True)),
                ('estadoRol', models.CharField(max_length=10)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles', verbose_name='identificador de erol')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DataUser', verbose_name='identificador de usuario')),
            ],
        ),
    ]
