# Generated by Django 2.2.12 on 2020-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20200512_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='addData',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='datauser',
            name='apellidoUser',
            field=models.CharField(max_length=255, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='datauser',
            name='generoUser',
            field=models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro')], default='Otro', max_length=20),
        ),
        migrations.AddField(
            model_name='datauser',
            name='nombreUser',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='datauser',
            name='profesion',
            field=models.CharField(max_length=100, null=True, verbose_name='Profesion'),
        ),
        migrations.AddField(
            model_name='datauser',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado el'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='idUser',
            field=models.CharField(max_length=20, verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='telUser',
            field=models.CharField(max_length=20, verbose_name='Nunero de telefono'),
        ),
    ]
