# Generated by Django 2.2.12 on 2020-05-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20200514_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='fotoUser',
            field=models.ImageField(default='user.png', upload_to='perfiles/img', verbose_name='Foto de perfil'),
        ),
    ]
