# Generated by Django 2.2.12 on 2020-05-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0003_auto_20200514_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=100, verbose_name='Lenguaje')),
                ('motorDB', models.CharField(max_length=100, verbose_name='MotorDB')),
                ('arquitectura', models.CharField(max_length=100, verbose_name='Arquitectura de software')),
            ],
            options={
                'verbose_name': 'Categoria proyecto',
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoDoc', models.CharField(max_length=100, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipos documento',
                'verbose_name_plural': 'Tipo de documento',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=100, verbose_name='Nombre del proyecto')),
                ('descripcionProyecto', models.TextField(verbose_name='Descripcion del proyecto')),
                ('imagenProyecto', models.ImageField(default='proyecto.png', upload_to='', verbose_name='Imagen de proyecto')),
                ('fechaInicio', models.DateTimeField(verbose_name='Inicio del proyecto')),
                ('fechaFinal', models.DateTimeField(verbose_name='Fecha final')),
                ('urlProyecto', models.CharField(max_length=255, verbose_name='Directorio')),
                ('estadoProyecto', models.CharField(max_length=45, verbose_name='Estado')),
                ('idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Categoria', verbose_name='Identificador de categoria')),
            ],
            options={
                'verbose_name': 'Datos del proyecto',
                'verbose_name_plural': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDoc', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('patchDoc', models.CharField(max_length=200, verbose_name='Patch')),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto', verbose_name='Identificador de Proyecto')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.TipoDoc', verbose_name='Identificador de tipoDocu')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DataUser', verbose_name='Identificador de usuario')),
            ],
            options={
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documento',
            },
        ),
    ]
